CREATE TABLE IF NOT EXISTS xbt_config (
  name VARCHAR(255) NOT NULL,
  value VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS xbt_torrents (
  tid INT UNSIGNED NOT NULL AUTO_INCREMENT,
  info_hash BINARY(20) NOT NULL,
  seeders INT UNSIGNED NOT NULL DEFAULT 0,
  leechers INT UNSIGNED NOT NULL DEFAULT 0,
  completed INT UNSIGNED NOT NULL DEFAULT 0,
  flags INT UNSIGNED NOT NULL DEFAULT 0,
  mtime INT UNSIGNED NOT NULL DEFAULT 0,
  ctime INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (tid),
  UNIQUE KEY uq_xbt_torrents_info_hash (info_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS xbt_users (
  uid INT UNSIGNED NOT NULL,
  can_leech TINYINT UNSIGNED NOT NULL DEFAULT 1,
  wait_time INT UNSIGNED NOT NULL DEFAULT 0,
  peers_limit INT UNSIGNED NOT NULL DEFAULT 0,
  torrents_limit INT UNSIGNED NOT NULL DEFAULT 0,
  torrent_pass CHAR(32) NOT NULL,
  torrent_pass_version INT UNSIGNED NOT NULL DEFAULT 0,
  downloaded BIGINT UNSIGNED NOT NULL DEFAULT 0,
  uploaded BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (uid),
  UNIQUE KEY uq_xbt_users_torrent_pass (torrent_pass)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS xbt_peers (
  tid INT UNSIGNED NOT NULL,
  uid INT UNSIGNED NOT NULL,
  active TINYINT UNSIGNED NOT NULL DEFAULT 0,
  announced INT UNSIGNED NOT NULL DEFAULT 0,
  completed INT UNSIGNED NOT NULL DEFAULT 0,
  downloaded BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `left` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  uploaded BIGINT UNSIGNED NOT NULL DEFAULT 0,
  mtime INT UNSIGNED NOT NULL DEFAULT 0,
  peer_id BINARY(20) NOT NULL,
  event TINYINT UNSIGNED NOT NULL DEFAULT 0,
  ip INT UNSIGNED NOT NULL DEFAULT 0,
  port SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (tid, uid),
  KEY ix_xbt_peers_uid_active (uid, active),
  KEY ix_xbt_peers_uid_completed_active (uid, completed, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
