# Generated by Django 5.2.13 on 2026-04-08 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releasefile',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='releases.release'),
        ),
        migrations.AddField(
            model_name='release',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='releases', to='releases.tag'),
        ),
    ]
