[metadata]
schema_version = "2.0.0"

[logging]
threshold = "info"

[core]
inactive_peer_cleanup_interval = 600
listed = true
private = true
tracker_usage_statistics = true

[core.announce_policy]
interval = 120
interval_min = 120

[core.database]
driver = "sqlite3"
path = "/var/lib/torrust/tracker/database/sqlite3.db"

[core.net]
external_ip = "0.0.0.0"
on_reverse_proxy = false

[core.tracker_policy]
max_peer_timeout = 900
persistent_torrent_completed_stat = true
remove_peerless_torrents = true

[health_check_api]
bind_address = "0.0.0.0:1313"

[http_api]
bind_address = "0.0.0.0:1212"

[http_api.access_tokens]
admin = "change-me"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[[udp_trackers]]
bind_address = "0.0.0.0:6969"
