# Generated by Django 5.2.13 on 2026-04-17 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_invitecode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passkey",
        ),
    ]
