# Generated by Django 5.2.13 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_passkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tracker_key_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tracker_passkey",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
