# Generated by Django 5.2.13 on 2026-05-08 15:49

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_tracker_key_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
    ]
