# Generated by Django 5.2.13 on 2026-04-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XbtFileMirror',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('info_hash', models.BinaryField(max_length=20, unique=True)),
                ('leechers', models.PositiveIntegerField(default=0)),
                ('seeders', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('flags', models.PositiveIntegerField(default=0)),
                ('mtime', models.PositiveIntegerField(default=0)),
                ('ctime', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'xbt_torrents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XbtUserMirror',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('torrent_pass', models.CharField(max_length=32, unique=True)),
                ('can_leech', models.BooleanField(default=True)),
                ('downloaded', models.BigIntegerField(default=0)),
                ('uploaded', models.BigIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'xbt_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', '用户'), ('release', '资源'), ('full', '全量')], max_length=20)),
                ('target_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', '成功'), ('warning', '警告'), ('failed', '失败')], max_length=20)),
                ('message', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_sync_logs', to='releases.release')),
            ],
            options={
                'db_table': 'tracker_sync_logs',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
