# Generated by Django 5.2.13 on 2026-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_sync", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XbtFileCompatMirror",
            fields=[
                ("tid", models.AutoField(primary_key=True, serialize=False)),
                ("info_hash", models.BinaryField(max_length=20, unique=True)),
                ("leechers", models.PositiveIntegerField(default=0)),
                ("seeders", models.PositiveIntegerField(default=0)),
                ("completed", models.PositiveIntegerField(default=0)),
                ("flags", models.PositiveIntegerField(default=0)),
                ("mtime", models.PositiveIntegerField(default=0)),
                ("ctime", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "xbt_files",
                "managed": False,
            },
        ),
    ]
