# Generated by Django 5.2.13 on 2026-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('online', '上线'), ('draft', '草稿'), ('offline', '下线')], default='draft', max_length=20)),
                ('audience', models.CharField(choices=[('all', '全部'), ('uploader', '上传者'), ('admin', '管理员')], default='all', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='字幕组分流站', max_length=120)),
                ('site_description', models.CharField(default='内部资源浏览、下载与 RSS 订阅入口', max_length=255)),
                ('login_notice', models.TextField(blank=True)),
                ('rss_base_path', models.CharField(default='/rss', max_length=255)),
                ('download_notice', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
                'db_table': 'site_settings',
            },
        ),
    ]
