# Generated by Django 5.2.13 on 2026-05-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("releases", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerTorrentSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("infohash", models.CharField(max_length=40)),
                ("is_whitelisted", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_scrape_at", models.DateTimeField(blank=True, null=True)),
                ("last_scrape_seeders", models.PositiveIntegerField(default=0)),
                ("last_scrape_leechers", models.PositiveIntegerField(default=0)),
                ("last_scrape_completed", models.PositiveIntegerField(default=0)),
                (
                    "release",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracker_sync",
                        to="releases.release",
                    ),
                ),
            ],
            options={
                "db_table": "tracker_torrent_sync",
                "ordering": ["-last_synced_at", "-id"],
            },
        ),
    ]
